services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - notes-app
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

  backend:
    build: ./notes-app-rest
    container_name: notes-app-rest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: notesdb
    depends_on:
      - mysql
    networks:
      - notes-app

  frontend:
    build: ./notes-app-web
    container_name: notes-app-web
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - notes-app

volumes:
  mysql_data:

networks:
  notes-app:
    name: notes-app